import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface Pet {
    name: string;
    breed: string | null;
    age: number | null;
    gender: string | null;
    weight: number | null;
    photo_url: string | null;
}

interface TimelineEntry {
    date: string;
    category: string;
    title: string;
    description: string;
    metadata: any;
}

interface FileEntry {
    entry_id: string;
    file_name: string;
    file_type: string;
}

export const generatePetReport = async (
    pet: Pet,
    entries: TimelineEntry[],
    files: FileEntry[]
) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Cover Page / Header Section
    // Photo (if exists, circular placeholder for now as loading images in jspdf is async/complex)
    doc.setFillColor(242, 250, 253); // Soft blue background for header
    doc.rect(0, 0, pageWidth, 60, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.setTextColor(14, 47, 68); // #0E2F44
    doc.text(pet.name, pageWidth / 2, 35, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(111, 138, 150); // #6F8A96
    const subtitle = `${pet.breed || 'Unknown Breed'} • ${pet.age || '?'} Years • ${pet.gender || 'Unknown'}`;
    doc.text(subtitle, pageWidth / 2, 45, { align: 'center' });

    // Quick Stats Section
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(73, 179, 232); // #49B3E8
    doc.text('Health Overview', 20, 75);

    const lastVet = entries.find(e => e.category === 'vet_visit')?.date || 'N/A';
    const lastVaccine = entries.find(e => e.category === 'vaccine')?.date || 'N/A';

    autoTable(doc, {
        startY: 80,
        head: [],
        body: [
            ['Total Entries', entries.length.toString(), 'Current Weight', `${pet.weight || 'N/A'} kg`],
            ['Last Vet Visit', lastVet, 'Last Vaccine', lastVaccine],
        ],
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 5, textColor: [14, 47, 68] },
        columnStyles: {
            0: { fontStyle: 'bold', textColor: [111, 138, 150] },
            2: { fontStyle: 'bold', textColor: [111, 138, 150] },
        }
    });

    // Timeline Section
    doc.setFontSize(14);
    doc.setTextColor(73, 179, 232);
    doc.text('Medical Timeline', 20, (doc as any).lastAutoTable.finalY + 15);

    const sortedEntries = [...entries].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    const tableData = sortedEntries.map(entry => {
        const entryFiles = files.filter(f => f.entry_id === (entry as any).id).map(f => f.file_name).join(', ');
        return [
            format(new Date(entry.date), 'MMM dd, yyyy'),
            entry.category.toUpperCase(),
            { content: `${entry.title}\n${entry.description}${entryFiles ? `\n\nAttachments: ${entryFiles}` : ''}`, styles: { cellPadding: 5 } }
        ];
    });

    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 20,
        head: [['Date', 'Category', 'Entry Details']],
        body: tableData,
        headStyles: { fillColor: [14, 47, 68], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [248, 250, 251] },
        styles: { fontSize: 9, cellPadding: 4, overflow: 'linebreak' },
        columnStyles: {
            0: { cellWidth: 30 },
            1: { cellWidth: 25, fontStyle: 'bold' },
        },
        didDrawPage: (data) => {
            // Footer
            doc.setFontSize(8);
            doc.setTextColor(111, 138, 150);
            doc.text(`Page ${data.pageNumber}`, pageWidth - 25, pageHeight - 10);
            doc.text(`Generated by PetVault – Your Pet’s Private Health Timeline • ${format(new Date(), 'yyyy-MM-dd')}`, 20, pageHeight - 10);
        }
    });

    doc.save(`${pet.name}_Health_Report.pdf`);
};
